export const initialState = {
  posts: [
    {
      id: "1",
      title: "Article title",
      shortDescription: "Short description of the article...",
      content: "Main content of the article",
      publishedDate: new Date("2023-03-16"),
      author: "John Doe",
    },
    {
      id: "2",
      title: "Article title",
      shortDescription: "Short description of the article...",
      content: "Main content of the article",
      publishedDate: new Date("2023-03-16"),
      author: "John Doe",
    },
    {
      id: "3",
      title: "Article title",
      shortDescription: "Short description of the article...",
      content: "Main content of the article",
      publishedDate: new Date("2023-03-16"),
      author: "John Doe",
    },
    {
      id: "4",
      title: "Article title",
      shortDescription: "Short description of the article...",
      content: "Main content of the article",
      publishedDate: new Date("2023-03-16"),
      author: "John Doe",
    },
    {
      id: "5",
      title: "Article title",
      shortDescription: "Short description of the article...",
      content: "Main content of the article",
      publishedDate: new Date("2023-03-16"),
      author: "John Doe",
    },
    {
      id: "6",
      title: "Article title",
      shortDescription: "Short description of the article...",
      content: "Main content of the article",
      publishedDate: new Date("2023-03-16"),
      author: "John Doe",
    },
  ],
};
